apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: genesis
resources:
  - namespace.yaml
  - configmap.yaml
  - secrets.example.yaml
  - api-deployment.yaml
  - api-service.yaml
  - hpa.yaml
  - ingress.yaml
  - postgres.yaml
  - redis.yaml
